[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:dotnet-server]
command=dotnet QCLab.dll
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/dotnet-server.err.log
stdout_logfile=/var/log/dotnet-server.out.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
