//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/QCFormula.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace QCFormula.ANTLRGenerated {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class QCFormulaParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T_ADD=1, T_SUB=2, T_MUL=3, T_DIV=4, T_POW=5, T_AND=6, T_OR=7, T_GT=8, 
		T_GTE=9, T_LT=10, T_LTE=11, T_EQ=12, T_NEQ=13, T_ASSIGN=14, T_LPAREN=15, 
		T_RPAREN=16, T_LDBRACK=17, T_RDBRACK=18, T_LBRACK=19, T_RBRACK=20, T_SEMICOLON=21, 
		T_COMMA=22, ID=23, NUMBER=24, COMMENT=25, WS=26;
	public const int
		RULE_prog = 0, RULE_statement = 1, RULE_assignment = 2, RULE_final_expression = 3, 
		RULE_expression = 4, RULE_atom = 5, RULE_arg_list = 6;
	public static readonly string[] ruleNames = {
		"prog", "statement", "assignment", "final_expression", "expression", "atom", 
		"arg_list"
	};

	private static readonly string[] _LiteralNames = {
		null, "'+'", "'-'", "'*'", "'/'", "'^'", "'&&'", "'||'", "'>'", "'>='", 
		"'<'", "'<='", "'=='", "'!='", "'='", "'('", "')'", "'[['", "']]'", "'['", 
		"']'", "';'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "T_ADD", "T_SUB", "T_MUL", "T_DIV", "T_POW", "T_AND", "T_OR", "T_GT", 
		"T_GTE", "T_LT", "T_LTE", "T_EQ", "T_NEQ", "T_ASSIGN", "T_LPAREN", "T_RPAREN", 
		"T_LDBRACK", "T_RDBRACK", "T_LBRACK", "T_RBRACK", "T_SEMICOLON", "T_COMMA", 
		"ID", "NUMBER", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "QCFormula.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static QCFormulaParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public QCFormulaParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public QCFormulaParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Final_expressionContext final_expression() {
			return GetRuleContext<Final_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(QCFormulaParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterProg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitProg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 17;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 14;
					statement();
					}
					} 
				}
				State = 19;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			}
			State = 20;
			final_expression();
			State = 21;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_SEMICOLON() { return GetToken(QCFormulaParser.T_SEMICOLON, 0); }
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 2, RULE_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 23;
			assignment();
			State = 24;
			Match(T_SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(QCFormulaParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_ASSIGN() { return GetToken(QCFormulaParser.T_ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 4, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 26;
			Match(ID);
			State = 27;
			Match(T_ASSIGN);
			State = 28;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Final_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_SEMICOLON() { return GetToken(QCFormulaParser.T_SEMICOLON, 0); }
		public Final_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_final_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterFinal_expression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitFinal_expression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFinal_expression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Final_expressionContext final_expression() {
		Final_expressionContext _localctx = new Final_expressionContext(Context, State);
		EnterRule(_localctx, 6, RULE_final_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 30;
			expression(0);
			State = 32;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T_SEMICOLON) {
				{
				State = 31;
				Match(T_SEMICOLON);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class AndExprContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_AND() { return GetToken(QCFormulaParser.T_AND, 0); }
		public AndExprContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterAndExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitAndExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAndExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MulDivExprContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_MUL() { return GetToken(QCFormulaParser.T_MUL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_DIV() { return GetToken(QCFormulaParser.T_DIV, 0); }
		public MulDivExprContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterMulDivExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitMulDivExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMulDivExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EqExprContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_EQ() { return GetToken(QCFormulaParser.T_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_NEQ() { return GetToken(QCFormulaParser.T_NEQ, 0); }
		public EqExprContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterEqExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitEqExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEqExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PowExprContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_POW() { return GetToken(QCFormulaParser.T_POW, 0); }
		public PowExprContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterPowExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitPowExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPowExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CompExprContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_GT() { return GetToken(QCFormulaParser.T_GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_GTE() { return GetToken(QCFormulaParser.T_GTE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_LT() { return GetToken(QCFormulaParser.T_LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_LTE() { return GetToken(QCFormulaParser.T_LTE, 0); }
		public CompExprContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterCompExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitCompExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AtomExprContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public AtomExprContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterAtomExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitAtomExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAtomExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AddSubExprContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_ADD() { return GetToken(QCFormulaParser.T_ADD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_SUB() { return GetToken(QCFormulaParser.T_SUB, 0); }
		public AddSubExprContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterAddSubExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitAddSubExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAddSubExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OrExprContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_OR() { return GetToken(QCFormulaParser.T_OR, 0); }
		public OrExprContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterOrExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitOrExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusExprContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_SUB() { return GetToken(QCFormulaParser.T_SUB, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public UnaryMinusExprContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterUnaryMinusExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitUnaryMinusExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinusExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 8;
		EnterRecursionRule(_localctx, 8, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 38;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T_SUB:
				{
				_localctx = new UnaryMinusExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 35;
				Match(T_SUB);
				State = 36;
				expression(9);
				}
				break;
			case T_LPAREN:
			case T_LDBRACK:
			case T_LBRACK:
			case ID:
			case NUMBER:
				{
				_localctx = new AtomExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 37;
				atom();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 63;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 61;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
					case 1:
						{
						_localctx = new PowExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 40;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 41;
						Match(T_POW);
						State = 42;
						expression(8);
						}
						break;
					case 2:
						{
						_localctx = new MulDivExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 43;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 44;
						_la = TokenStream.LA(1);
						if ( !(_la==T_MUL || _la==T_DIV) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 45;
						expression(8);
						}
						break;
					case 3:
						{
						_localctx = new AddSubExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 46;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 47;
						_la = TokenStream.LA(1);
						if ( !(_la==T_ADD || _la==T_SUB) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 48;
						expression(7);
						}
						break;
					case 4:
						{
						_localctx = new CompExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 49;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 50;
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 3840L) != 0)) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 51;
						expression(6);
						}
						break;
					case 5:
						{
						_localctx = new EqExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 52;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 53;
						_la = TokenStream.LA(1);
						if ( !(_la==T_EQ || _la==T_NEQ) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 54;
						expression(5);
						}
						break;
					case 6:
						{
						_localctx = new AndExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 55;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 56;
						Match(T_AND);
						State = 57;
						expression(4);
						}
						break;
					case 7:
						{
						_localctx = new OrExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 58;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 59;
						Match(T_OR);
						State = 60;
						expression(3);
						}
						break;
					}
					} 
				}
				State = 65;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
	 
		public AtomContext() { }
		public virtual void CopyFrom(AtomContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ParamExprContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_LBRACK() { return GetToken(QCFormulaParser.T_LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(QCFormulaParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_RBRACK() { return GetToken(QCFormulaParser.T_RBRACK, 0); }
		public ParamExprContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterParamExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitParamExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParamExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberExprContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(QCFormulaParser.NUMBER, 0); }
		public NumberExprContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterNumberExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitNumberExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class VarExprContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(QCFormulaParser.ID, 0); }
		public VarExprContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterVarExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitVarExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVarExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenExprContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_LPAREN() { return GetToken(QCFormulaParser.T_LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_RPAREN() { return GetToken(QCFormulaParser.T_RPAREN, 0); }
		public ParenExprContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterParenExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitParenExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ArrayParamExprContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_LDBRACK() { return GetToken(QCFormulaParser.T_LDBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(QCFormulaParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_RDBRACK() { return GetToken(QCFormulaParser.T_RDBRACK, 0); }
		public ArrayParamExprContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterArrayParamExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitArrayParamExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayParamExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncCallExprContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(QCFormulaParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_LPAREN() { return GetToken(QCFormulaParser.T_LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_RPAREN() { return GetToken(QCFormulaParser.T_RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Arg_listContext arg_list() {
			return GetRuleContext<Arg_listContext>(0);
		}
		public FuncCallExprContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterFuncCallExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitFuncCallExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncCallExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 10, RULE_atom);
		int _la;
		try {
			State = 84;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				_localctx = new ParenExprContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 66;
				Match(T_LPAREN);
				State = 67;
				expression(0);
				State = 68;
				Match(T_RPAREN);
				}
				break;
			case 2:
				_localctx = new ParamExprContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 70;
				Match(T_LBRACK);
				State = 71;
				Match(ID);
				State = 72;
				Match(T_RBRACK);
				}
				break;
			case 3:
				_localctx = new ArrayParamExprContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 73;
				Match(T_LDBRACK);
				State = 74;
				Match(ID);
				State = 75;
				Match(T_RDBRACK);
				}
				break;
			case 4:
				_localctx = new FuncCallExprContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 76;
				Match(ID);
				State = 77;
				Match(T_LPAREN);
				State = 79;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 25853956L) != 0)) {
					{
					State = 78;
					arg_list();
					}
				}

				State = 81;
				Match(T_RPAREN);
				}
				break;
			case 5:
				_localctx = new VarExprContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 82;
				Match(ID);
				}
				break;
			case 6:
				_localctx = new NumberExprContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 83;
				Match(NUMBER);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] T_COMMA() { return GetTokens(QCFormulaParser.T_COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_COMMA(int i) {
			return GetToken(QCFormulaParser.T_COMMA, i);
		}
		public Arg_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.EnterArg_list(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IQCFormulaListener typedListener = listener as IQCFormulaListener;
			if (typedListener != null) typedListener.ExitArg_list(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQCFormulaVisitor<TResult> typedVisitor = visitor as IQCFormulaVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArg_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Arg_listContext arg_list() {
		Arg_listContext _localctx = new Arg_listContext(Context, State);
		EnterRule(_localctx, 12, RULE_arg_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			expression(0);
			State = 91;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T_COMMA) {
				{
				{
				State = 87;
				Match(T_COMMA);
				State = 88;
				expression(0);
				}
				}
				State = 93;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 4: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 8);
		case 1: return Precpred(Context, 7);
		case 2: return Precpred(Context, 6);
		case 3: return Precpred(Context, 5);
		case 4: return Precpred(Context, 4);
		case 5: return Precpred(Context, 3);
		case 6: return Precpred(Context, 2);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,26,95,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,1,0,
		5,0,16,8,0,10,0,12,0,19,9,0,1,0,1,0,1,0,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,
		3,1,3,3,3,33,8,3,1,4,1,4,1,4,1,4,3,4,39,8,4,1,4,1,4,1,4,1,4,1,4,1,4,1,
		4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,5,4,62,8,4,10,
		4,12,4,65,9,4,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,3,5,
		80,8,5,1,5,1,5,1,5,3,5,85,8,5,1,6,1,6,1,6,5,6,90,8,6,10,6,12,6,93,9,6,
		1,6,0,1,8,7,0,2,4,6,8,10,12,0,4,1,0,3,4,1,0,1,2,1,0,8,11,1,0,12,13,104,
		0,17,1,0,0,0,2,23,1,0,0,0,4,26,1,0,0,0,6,30,1,0,0,0,8,38,1,0,0,0,10,84,
		1,0,0,0,12,86,1,0,0,0,14,16,3,2,1,0,15,14,1,0,0,0,16,19,1,0,0,0,17,15,
		1,0,0,0,17,18,1,0,0,0,18,20,1,0,0,0,19,17,1,0,0,0,20,21,3,6,3,0,21,22,
		5,0,0,1,22,1,1,0,0,0,23,24,3,4,2,0,24,25,5,21,0,0,25,3,1,0,0,0,26,27,5,
		23,0,0,27,28,5,14,0,0,28,29,3,8,4,0,29,5,1,0,0,0,30,32,3,8,4,0,31,33,5,
		21,0,0,32,31,1,0,0,0,32,33,1,0,0,0,33,7,1,0,0,0,34,35,6,4,-1,0,35,36,5,
		2,0,0,36,39,3,8,4,9,37,39,3,10,5,0,38,34,1,0,0,0,38,37,1,0,0,0,39,63,1,
		0,0,0,40,41,10,8,0,0,41,42,5,5,0,0,42,62,3,8,4,8,43,44,10,7,0,0,44,45,
		7,0,0,0,45,62,3,8,4,8,46,47,10,6,0,0,47,48,7,1,0,0,48,62,3,8,4,7,49,50,
		10,5,0,0,50,51,7,2,0,0,51,62,3,8,4,6,52,53,10,4,0,0,53,54,7,3,0,0,54,62,
		3,8,4,5,55,56,10,3,0,0,56,57,5,6,0,0,57,62,3,8,4,4,58,59,10,2,0,0,59,60,
		5,7,0,0,60,62,3,8,4,3,61,40,1,0,0,0,61,43,1,0,0,0,61,46,1,0,0,0,61,49,
		1,0,0,0,61,52,1,0,0,0,61,55,1,0,0,0,61,58,1,0,0,0,62,65,1,0,0,0,63,61,
		1,0,0,0,63,64,1,0,0,0,64,9,1,0,0,0,65,63,1,0,0,0,66,67,5,15,0,0,67,68,
		3,8,4,0,68,69,5,16,0,0,69,85,1,0,0,0,70,71,5,19,0,0,71,72,5,23,0,0,72,
		85,5,20,0,0,73,74,5,17,0,0,74,75,5,23,0,0,75,85,5,18,0,0,76,77,5,23,0,
		0,77,79,5,15,0,0,78,80,3,12,6,0,79,78,1,0,0,0,79,80,1,0,0,0,80,81,1,0,
		0,0,81,85,5,16,0,0,82,85,5,23,0,0,83,85,5,24,0,0,84,66,1,0,0,0,84,70,1,
		0,0,0,84,73,1,0,0,0,84,76,1,0,0,0,84,82,1,0,0,0,84,83,1,0,0,0,85,11,1,
		0,0,0,86,91,3,8,4,0,87,88,5,22,0,0,88,90,3,8,4,0,89,87,1,0,0,0,90,93,1,
		0,0,0,91,89,1,0,0,0,91,92,1,0,0,0,92,13,1,0,0,0,93,91,1,0,0,0,8,17,32,
		38,61,63,79,84,91
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace QCFormula.ANTLRGenerated
