//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/QCFormula.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace QCFormula.ANTLRGenerated {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class QCFormulaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T_ADD=1, T_SUB=2, T_MUL=3, T_DIV=4, T_POW=5, T_AND=6, T_OR=7, T_GT=8, 
		T_GTE=9, T_LT=10, T_LTE=11, T_EQ=12, T_NEQ=13, T_ASSIGN=14, T_LPAREN=15, 
		T_RPAREN=16, T_LDBRACK=17, T_RDBRACK=18, T_LBRACK=19, T_RBRACK=20, T_SEMICOLON=21, 
		T_COMMA=22, ID=23, NUMBER=24, COMMENT=25, WS=26;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T_ADD", "T_SUB", "T_MUL", "T_DIV", "T_POW", "T_AND", "T_OR", "T_GT", 
		"T_GTE", "T_LT", "T_LTE", "T_EQ", "T_NEQ", "T_ASSIGN", "T_LPAREN", "T_RPAREN", 
		"T_LDBRACK", "T_RDBRACK", "T_LBRACK", "T_RBRACK", "T_SEMICOLON", "T_COMMA", 
		"ID", "NUMBER", "COMMENT", "WS"
	};


	public QCFormulaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public QCFormulaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'+'", "'-'", "'*'", "'/'", "'^'", "'&&'", "'||'", "'>'", "'>='", 
		"'<'", "'<='", "'=='", "'!='", "'='", "'('", "')'", "'[['", "']]'", "'['", 
		"']'", "';'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "T_ADD", "T_SUB", "T_MUL", "T_DIV", "T_POW", "T_AND", "T_OR", "T_GT", 
		"T_GTE", "T_LT", "T_LTE", "T_EQ", "T_NEQ", "T_ASSIGN", "T_LPAREN", "T_RPAREN", 
		"T_LDBRACK", "T_RDBRACK", "T_LBRACK", "T_RBRACK", "T_SEMICOLON", "T_COMMA", 
		"ID", "NUMBER", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "QCFormula.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static QCFormulaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,26,143,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,
		7,14,2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,
		7,21,2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,1,0,1,0,1,1,1,1,1,2,1,2,1,
		3,1,3,1,4,1,4,1,5,1,5,1,5,1,6,1,6,1,6,1,7,1,7,1,8,1,8,1,8,1,9,1,9,1,10,
		1,10,1,10,1,11,1,11,1,11,1,12,1,12,1,12,1,13,1,13,1,14,1,14,1,15,1,15,
		1,16,1,16,1,16,1,17,1,17,1,17,1,18,1,18,1,19,1,19,1,20,1,20,1,21,1,21,
		1,22,1,22,5,22,108,8,22,10,22,12,22,111,9,22,1,23,4,23,114,8,23,11,23,
		12,23,115,1,23,1,23,4,23,120,8,23,11,23,12,23,121,3,23,124,8,23,1,24,1,
		24,1,24,1,24,5,24,130,8,24,10,24,12,24,133,9,24,1,24,1,24,1,25,4,25,138,
		8,25,11,25,12,25,139,1,25,1,25,0,0,26,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,
		8,17,9,19,10,21,11,23,12,25,13,27,14,29,15,31,16,33,17,35,18,37,19,39,
		20,41,21,43,22,45,23,47,24,49,25,51,26,1,0,5,3,0,65,90,95,95,97,122,4,
		0,48,57,65,90,95,95,97,122,1,0,48,57,2,0,10,10,13,13,3,0,9,10,13,13,32,
		32,148,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,
		1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,
		0,0,23,1,0,0,0,0,25,1,0,0,0,0,27,1,0,0,0,0,29,1,0,0,0,0,31,1,0,0,0,0,33,
		1,0,0,0,0,35,1,0,0,0,0,37,1,0,0,0,0,39,1,0,0,0,0,41,1,0,0,0,0,43,1,0,0,
		0,0,45,1,0,0,0,0,47,1,0,0,0,0,49,1,0,0,0,0,51,1,0,0,0,1,53,1,0,0,0,3,55,
		1,0,0,0,5,57,1,0,0,0,7,59,1,0,0,0,9,61,1,0,0,0,11,63,1,0,0,0,13,66,1,0,
		0,0,15,69,1,0,0,0,17,71,1,0,0,0,19,74,1,0,0,0,21,76,1,0,0,0,23,79,1,0,
		0,0,25,82,1,0,0,0,27,85,1,0,0,0,29,87,1,0,0,0,31,89,1,0,0,0,33,91,1,0,
		0,0,35,94,1,0,0,0,37,97,1,0,0,0,39,99,1,0,0,0,41,101,1,0,0,0,43,103,1,
		0,0,0,45,105,1,0,0,0,47,113,1,0,0,0,49,125,1,0,0,0,51,137,1,0,0,0,53,54,
		5,43,0,0,54,2,1,0,0,0,55,56,5,45,0,0,56,4,1,0,0,0,57,58,5,42,0,0,58,6,
		1,0,0,0,59,60,5,47,0,0,60,8,1,0,0,0,61,62,5,94,0,0,62,10,1,0,0,0,63,64,
		5,38,0,0,64,65,5,38,0,0,65,12,1,0,0,0,66,67,5,124,0,0,67,68,5,124,0,0,
		68,14,1,0,0,0,69,70,5,62,0,0,70,16,1,0,0,0,71,72,5,62,0,0,72,73,5,61,0,
		0,73,18,1,0,0,0,74,75,5,60,0,0,75,20,1,0,0,0,76,77,5,60,0,0,77,78,5,61,
		0,0,78,22,1,0,0,0,79,80,5,61,0,0,80,81,5,61,0,0,81,24,1,0,0,0,82,83,5,
		33,0,0,83,84,5,61,0,0,84,26,1,0,0,0,85,86,5,61,0,0,86,28,1,0,0,0,87,88,
		5,40,0,0,88,30,1,0,0,0,89,90,5,41,0,0,90,32,1,0,0,0,91,92,5,91,0,0,92,
		93,5,91,0,0,93,34,1,0,0,0,94,95,5,93,0,0,95,96,5,93,0,0,96,36,1,0,0,0,
		97,98,5,91,0,0,98,38,1,0,0,0,99,100,5,93,0,0,100,40,1,0,0,0,101,102,5,
		59,0,0,102,42,1,0,0,0,103,104,5,44,0,0,104,44,1,0,0,0,105,109,7,0,0,0,
		106,108,7,1,0,0,107,106,1,0,0,0,108,111,1,0,0,0,109,107,1,0,0,0,109,110,
		1,0,0,0,110,46,1,0,0,0,111,109,1,0,0,0,112,114,7,2,0,0,113,112,1,0,0,0,
		114,115,1,0,0,0,115,113,1,0,0,0,115,116,1,0,0,0,116,123,1,0,0,0,117,119,
		5,46,0,0,118,120,7,2,0,0,119,118,1,0,0,0,120,121,1,0,0,0,121,119,1,0,0,
		0,121,122,1,0,0,0,122,124,1,0,0,0,123,117,1,0,0,0,123,124,1,0,0,0,124,
		48,1,0,0,0,125,126,5,47,0,0,126,127,5,47,0,0,127,131,1,0,0,0,128,130,8,
		3,0,0,129,128,1,0,0,0,130,133,1,0,0,0,131,129,1,0,0,0,131,132,1,0,0,0,
		132,134,1,0,0,0,133,131,1,0,0,0,134,135,6,24,0,0,135,50,1,0,0,0,136,138,
		7,4,0,0,137,136,1,0,0,0,138,139,1,0,0,0,139,137,1,0,0,0,139,140,1,0,0,
		0,140,141,1,0,0,0,141,142,6,25,0,0,142,52,1,0,0,0,7,0,109,115,121,123,
		131,139,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace QCFormula.ANTLRGenerated
