//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/QCFormula.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace QCFormula.ANTLRGenerated {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IQCFormulaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class QCFormulaBaseListener : IQCFormulaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="QCFormulaParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] QCFormulaParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QCFormulaParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] QCFormulaParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QCFormulaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] QCFormulaParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QCFormulaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] QCFormulaParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QCFormulaParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] QCFormulaParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QCFormulaParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] QCFormulaParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QCFormulaParser.final_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFinal_expression([NotNull] QCFormulaParser.Final_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QCFormulaParser.final_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFinal_expression([NotNull] QCFormulaParser.Final_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] QCFormulaParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] QCFormulaParser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDivExpr([NotNull] QCFormulaParser.MulDivExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDivExpr([NotNull] QCFormulaParser.MulDivExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EqExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqExpr([NotNull] QCFormulaParser.EqExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EqExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqExpr([NotNull] QCFormulaParser.EqExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PowExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPowExpr([NotNull] QCFormulaParser.PowExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PowExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPowExpr([NotNull] QCFormulaParser.PowExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CompExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompExpr([NotNull] QCFormulaParser.CompExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CompExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompExpr([NotNull] QCFormulaParser.CompExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AtomExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomExpr([NotNull] QCFormulaParser.AtomExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AtomExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomExpr([NotNull] QCFormulaParser.AtomExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubExpr([NotNull] QCFormulaParser.AddSubExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubExpr([NotNull] QCFormulaParser.AddSubExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] QCFormulaParser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] QCFormulaParser.OrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryMinusExpr([NotNull] QCFormulaParser.UnaryMinusExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryMinusExpr([NotNull] QCFormulaParser.UnaryMinusExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExpr([NotNull] QCFormulaParser.ParenExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExpr([NotNull] QCFormulaParser.ParenExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParamExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamExpr([NotNull] QCFormulaParser.ParamExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParamExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamExpr([NotNull] QCFormulaParser.ParamExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayParamExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayParamExpr([NotNull] QCFormulaParser.ArrayParamExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayParamExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayParamExpr([NotNull] QCFormulaParser.ArrayParamExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FuncCallExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCallExpr([NotNull] QCFormulaParser.FuncCallExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FuncCallExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCallExpr([NotNull] QCFormulaParser.FuncCallExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarExpr([NotNull] QCFormulaParser.VarExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarExpr([NotNull] QCFormulaParser.VarExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberExpr([NotNull] QCFormulaParser.NumberExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberExpr([NotNull] QCFormulaParser.NumberExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QCFormulaParser.arg_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg_list([NotNull] QCFormulaParser.Arg_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QCFormulaParser.arg_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg_list([NotNull] QCFormulaParser.Arg_listContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace QCFormula.ANTLRGenerated
