//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/QCFormula.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace QCFormula.ANTLRGenerated {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="QCFormulaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IQCFormulaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="QCFormulaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] QCFormulaParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QCFormulaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] QCFormulaParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QCFormulaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] QCFormulaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QCFormulaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] QCFormulaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QCFormulaParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] QCFormulaParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QCFormulaParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] QCFormulaParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QCFormulaParser.final_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinal_expression([NotNull] QCFormulaParser.Final_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QCFormulaParser.final_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinal_expression([NotNull] QCFormulaParser.Final_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] QCFormulaParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] QCFormulaParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivExpr([NotNull] QCFormulaParser.MulDivExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivExpr([NotNull] QCFormulaParser.MulDivExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EqExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqExpr([NotNull] QCFormulaParser.EqExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EqExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqExpr([NotNull] QCFormulaParser.EqExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PowExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPowExpr([NotNull] QCFormulaParser.PowExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PowExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPowExpr([NotNull] QCFormulaParser.PowExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CompExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompExpr([NotNull] QCFormulaParser.CompExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CompExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompExpr([NotNull] QCFormulaParser.CompExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AtomExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomExpr([NotNull] QCFormulaParser.AtomExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AtomExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomExpr([NotNull] QCFormulaParser.AtomExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSubExpr([NotNull] QCFormulaParser.AddSubExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSubExpr([NotNull] QCFormulaParser.AddSubExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] QCFormulaParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] QCFormulaParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryMinusExpr([NotNull] QCFormulaParser.UnaryMinusExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryMinusExpr([NotNull] QCFormulaParser.UnaryMinusExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] QCFormulaParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] QCFormulaParser.ParenExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParamExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamExpr([NotNull] QCFormulaParser.ParamExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParamExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamExpr([NotNull] QCFormulaParser.ParamExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayParamExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayParamExpr([NotNull] QCFormulaParser.ArrayParamExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayParamExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayParamExpr([NotNull] QCFormulaParser.ArrayParamExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FuncCallExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCallExpr([NotNull] QCFormulaParser.FuncCallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FuncCallExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCallExpr([NotNull] QCFormulaParser.FuncCallExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarExpr([NotNull] QCFormulaParser.VarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarExpr([NotNull] QCFormulaParser.VarExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberExpr([NotNull] QCFormulaParser.NumberExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberExpr</c>
	/// labeled alternative in <see cref="QCFormulaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberExpr([NotNull] QCFormulaParser.NumberExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QCFormulaParser.arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg_list([NotNull] QCFormulaParser.Arg_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QCFormulaParser.arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg_list([NotNull] QCFormulaParser.Arg_listContext context);
}
} // namespace QCFormula.ANTLRGenerated
